spring:
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:postgresql://emsp-db.c9ik4gyckpnn.ap-northeast-1.rds.amazonaws.com:5432/emsp_db  # 指向 Docker 容器
    username: emsp
    password: emsp123999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate  # 禁止 Hibernate 自动建表
    show-sql: true              # 控制台打印 SQL
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: validate
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 20

  flyway:
    enabled: true
    locations: classpath:db/migration  # Flyway 脚本路径
    baseline-on-migrate: true  # 允许空数据库初始化
    clean-disabled: false   # 允许执行clean命令
#    validate-on-migrate: true   # 开发环境关闭校验
