name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request: # 添加 pull_request 触发器
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置Java环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 缓存Maven依赖，加速构建
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 编译和单元测试 - 使用package而非install
      - name: Build and test
        run: mvn clean verify  # 这是最佳选择，后面有解释
        # 如果想在测试失败时看到详细日志:
        # run: mvn -B clean verify --no-transf

      # 添加测试报告
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always() # 即使测试失败也生成报告
        with:
          name: Maven Test Results
          path: target/surefire-reports/*.xml
          reporter: java-junit

        # 代码覆盖率报告
      - name: Generate Coverage Report
        run: mvn jacoco:report

      # 代码质量检查示例
#      - name: Run SonarCloud
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 添加在测试通过后
      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .

      - name: Save Docker image
        run: docker save myapp:${{ github.sha }} -o image.tar
        if: ${{ success() }} # 仅测试通过时构建

      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar