name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request: # 添加 pull_request 触发器
    branches: [master]

jobs:
  build-and-test:
    permissions:
      checks: write
      actions: read
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth:0 # 获取完整历史记录

      # 设置Java环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 缓存Maven依赖，加速构建
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 编译和单元测试 - 使用package而非install
      - name: Build and test
        run: mvn clean verify  # 这是最佳选择，后面有解释
        # 如果想在测试失败时看到详细日志:
        # run: mvn -B clean verify --no-transf

      # 添加测试报告
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always() # 即使测试失败也生成报告
        with:
          name: Maven Test Results
          path: target/surefire-reports/*.xml
          reporter: java-junit

        # 代码覆盖率报告
      - name: Generate Coverage Report
        run: mvn jacoco:report

      # 代码质量检查示例
#      - name: Run SonarCloud
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Docker 构建（添加依赖检测，确保镜像存在）
      - name: Build Docker image
        id: docker-build
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            docker build -t myapp:${{ github.sha }} .
          else
            echo "test failed,skip the docker build."
            exit 1
          fi

      - name: Save Docker image
        if: steps.docker-build.outcome == 'success'
        run: docker save myapp:${{ github.sha }} -o image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar